In [22]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from statsmodels.formula.api import ols
from scipy.stats import binom, t, sem,ttest_ind,ttest_1samp
from sklearn.utils import resample
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
from sklearn.model_selection import LeaveOneOut
import scipy.stats as st
data = pd.read_csv("Humerus.txt", sep = "\s+")
data.head()

humerus  code
0      659     1
1      689     1
2      703     1
3      702     1
4      709     1

### Exercise 1

In [15]:
group1 = data.iloc[:26, 0]
group2 = data.iloc[26:, 0]

k = 1000
sim1_samples = np.random.choice(group1,(k,len(group1)),replace=True)
sim2_samples = np.random.choice(group2,(k,len(group2)),replace=True)

sim_mean_dead = np.mean(sim1_samples,axis=1)
sim_mean_alive = np.mean(sim2_samples,axis=1)
sim_mean_diff = sim_mean_dead-sim_mean_alive

conf_dead = np.quantile(sim_mean_dead,[0.025,0.975])
conf_alive = np.quantile(sim_mean_alive,[0.025,0.975])
conf_diff = np.quantile(sim_mean_diff,[0.025,0.975])
conf_dead,conf_alive,conf_diff

(array([715.49903846, 733.77211538]),
 array([734.48484848, 746.48712121]),
 array([-26.35518648,  -4.65748834]))

### Exercise 2

In [43]:
conf_norm_1 = st.norm.interval (loc=np.mean(group1), scale=st.sem(group1),confidence=0.95) 
conf_norm_2 = st.norm.interval (loc=np.mean(group2), scale=st.sem(group2),confidence=0.95) 
diff = group1-group2
conf_norm_diff = st.norm.interval (loc=np.mean(abs(group1-group2)), scale=st.sem(abs(group1-group2)),confidence=0.95) 
conf_norm_1,conf_norm_2

((716.0082020626093, 734.7610287066215),
 (734.7796555144929, 746.4324656976283))